apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - targetPort: {{ .Values.backend.port }}
      port: {{ .Values.backend.port }}
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - targetPort: {{ .Values.frontend.port }}
      port: {{ .Values.frontend.port }}
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - targetPort: {{ .Values.database.port }}
      port: {{ .Values.database.port }}