apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
  namespace: {{ .Values.global.namespace }}

type: Opaque
data:
  postgres-password: {{ .Values.database.secret.password }}
  postgres-user: {{ .Values.database.secret.user }}
  postgres-db: {{ .Values.database.secret.db }}
  postgres-host: {{ .Values.database.secret.host }}