apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - image: {{ .Values.backend.image }}
          name: {{ .Release.Name }}-backend
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources:
            requests:
              cpu: {{ .Values.backend.req.cpu }}
              memory: {{ .Values.backend.req.memory }}
            limits:
              cpu: {{ .Values.backend.lim.cpu }}
              memory: {{ .Values.backend.lim.memory }}     
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
                  key: postgres-db 
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
                  key: postgres-host 
            - name: DB_CONN
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
            - name: UVICORN_PORT
              value: "{{ .Values.backend.uvicornPort }}"
            - name: BACKEND_VERSION
              value: {{ .Values.backend.version }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: {{ .Values.backend.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}