apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-db
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:   
      containers:
        - image: {{ .Values.database.image }}
          name: {{ .Release.Name }}-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-user
                  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: postgres-db
                  name: {{ .Release.Name }}-{{ .Values.database.secretName }}
          ports:
          - containerPort: {{ .Values.database.port }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: {{ .Values.database.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.database.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.database.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.database.livenessProbe.failureThreshold }}
          resources:
            limits:  
              cpu: {{ .Values.database.lim.cpu }}
              memory: {{ .Values.database.lim.memory }}
            requests:
              cpu: {{ .Values.database.req.cpu }}
              memory: {{ .Values.database.req.memory }}
          volumeMounts:
            - name: volume-db
              mountPath: {{ .Values.database.mountPath }}
      volumes:
        - name: volume-db
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc-db
    